# Generated by Django 4.2 on 2023-05-30 11:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feedback', '0004_favorite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorite',
            old_name='posts',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='favorite',
            old_name='users',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'post')},
        ),
    ]
