# Generated by Django 4.2 on 2023-05-26 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0006_post_floor_alter_post_realty_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.post', verbose_name='пост'),
        ),
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
    ]
