# Generated by Django 4.2 on 2023-05-26 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0007_commentary_post_alter_commentary_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
            preserve_default=False,
        ),
    ]
